tname: atlas-dijet-ml
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.9
  
  # Core scientific computing
  - numpy>=1.19.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  
  # Machine learning
  - scikit-learn>=1.0.0
  - xgboost>=1.5.0
  
  # Deep learning (PyTorch)
  - pytorch>=2.3.0
  - torchvision>=0.18.0
  - torchaudio>=2.3.0
  
  # Data handling
  - h5py>=3.0.0
  - zarr>=2.8.0
  
  # Visualization
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # Progress and utilities
  - tqdm>=4.62.0
  - psutil>=5.8.0
  - pyyaml>=5.4.0
  - click>=8.0.0
  
  # Development tools
  - pytest>=6.0.0
  - black
  - isort
  - flake8
  
  # Jupyter
  - jupyter
  - ipywidgets
  
  # Distributed computing
  - dask
  - distributed
  
  # Pip dependencies (not available in conda)
  - pip
  - pip:
    - uproot>=4.0.0
    - awkward>=1.5.0
    - joblib>=1.1.0
